version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestPubDepSceProject
  gitServerName: lakshitha
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: Lakshitha-Ramesh-IBM
  gitBranch: main
- name: WmAmazonSQSProvider
  version: 12.0.0.0.14
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
  wpmVersion: latest
services:
- serviceName: project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: TestPubDepSceProject
    version: "1.0"
  - name: WmAmazonSQSProvider
    version: 12.0.0.0.14
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.testpubdepsce.integrations:sqs2
  packages:
  - name: TestPubDepSceProject
    version: "1.0"
  - name: WmAmazonSQSProvider
    version: 12.0.0.0.14
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: wm.com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105.operations:ListQueues
  packages:
  - name: WmAmazonSQSProvider
    version: 12.0.0.0.14
configurationVariables:
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : ORACLE
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.connectTimeout
  : "30000"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.aws.accessKey
  : AKIA4CO5TWR6Q6LYDCNI
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.useChunking
  : "false"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.poolable
  : "false"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.retryCount
  : "4"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.enableCompression
  : "false"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.tcpNoDelay
  : "false"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.aws.durationSeconds
  : "3600"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.allowCircularRedirects
  : "true"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : ORCL
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.serverRedirectMax
  : "5"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : JDBC_BVT
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.aws.secretKey
  : "{AES}xq6NV6GY8b7pp90PtLGYJ3Le14Zf2TSN6f+W5DZhtbieAokPxTVUsmspPQ/QhOpU"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.readTimeout
  : "30000"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.providerUrl
  : http://sqs.us-east-1.amazonaws.com
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.enableSNI
  : "true"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.validateAfterInactivity
  : "1000"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}pFGqHdsr7K4IiCECQo+0SQ=="
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.timeoutType
  : none
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.userAgent
  : Cloudstreams
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.poolIncrementSize
  : "1"
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : tcp
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.keepAliveInterval
  : "-1"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..testpubdepsce..WmAmazonSQSProvider..com_webmethods_cloudstreams_amazon_sqs_aws4_v20121105..connections:amazonsqs2.pr.protocolVersion
  : HTTP/1.1
  ? artConnection.TestPubDepSceProject.project.testpubdepsce.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1521"
